#!/bin/sh

for HOST
do
   for file in "$HOST"/disks/ufs/fstyp*
   do
      if [ ! -r "$file" ] ;then
         echo "$HOST/ok/no fstyp output found"
         continue
      fi

      grep '^file system state' "$file" | while read state
      do
         case $state in
            *-3)
               echo "$HOST/ok/$state"
               ;;
            *) 
               echo "$HOST/err/$state"
               ;;
         esac
      done
   done
done
