#!/usr/bin/env perl

use strict;
use warnings;
use v5.8;

for my $HOST (@ARGV) {
   my $ok = 1;
   open my $fh, "<", "$HOST/disks/df-kl.out" or die $!;

   while (defined($_ = <$fh>)) {
      chomp;

      # Skip headings
      /^Filesystem\b/ and next;

      my ($fs, $kbytes, $used, $avail, $capacity, $mnt) = split / +/;
      s/ +/ /g;
      my $status = $_;

      # Skip empty FS
      next if $capacity eq "0%";

      $capacity =~ s/[^\d]//g;

      $ok = 0, print "$HOST/warn/$status\n" if
      $capacity >= 90 && $mnt !~ m{^/cdrom/};
   }

   print "$HOST/ok/all filesystems are good\n" if $ok;

   close $fh;
}
