#!/bin/sh

for HOST
do
   awk 'BEGIN{ok = 1}
   $6+$8+$9+$10 > 10{ print HOST"/err/"$0; ok = 0 }
   END{if(ok == 1){ print HOST"/ok/error counters are too low" } }
   ' HOST="$HOST" "$HOST"/netinfo/netstat-in.out
done
