#!/bin/sh

for HOST
do
   awk -v HOST="$HOST" 'BEGIN{ok = 1}
   END{if(ok == 1){ print HOST"/ok/error counters are too low" } }
   $6+$8+$9+$10 > 10{ print HOST"/err/"$0; ok = 0 }
   ' "$HOST"/netinfo/netstat-in.out
done
